[build]
  command = ""
  publish = "netlify"

[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://buscador.hostweb.workers.dev"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"