[build]
  command = ""
  publish = "netlify"

[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://businessasesores.web.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[functions]
  "check-domain" = "check-domain.js"