[build]
  command = ""
  publish = "netlify"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
     'Access-Control-Allow-Origin': allowedOrigin,
     'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
     'Access-Control-Allow-Headers': 'Authorization, Content-Type',